name: "growthcues_core"
version: "1.0.0"
config-version: 2

profile: "growthcues_core"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

vars:
  session_timeout_minutes: 30 # Session timeout duration in minutes
  group_id: "context_group_id" # Group ID (account_id) field in Segment data; by default, Segment stores this in 'context_group_id' if following standard conventions (B2B Spec)
  enable_identity_stitching: false # Set to false to disable identity stitching (if you don't have anonymous users or identifies table)
  identity_anonymous_id_field: "anonymousId" # Field name for anonymous ID in identity stitching; e.g., anonymousId (Segment default), visitor_id, device_id
  identity_lookback_days: 365 # Number of days to look back for identity resolution data
  tracks_lookback_days: 365 # Number of days to look back for tracks/events data
  pages_lookback_days: 365 # Number of days to look back for pages data
  include_pages_in_sessions: false # Set to true to include page views in session calculation

models:
  growthcues_core:
    # Config for all models in the project
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
    marts:
      +materialized: table
